---
include:
  - board: xiao_ble//zmk
    shield: skreecustom_left nice_view_adapter nice_view
  - board: xiao_ble//zmk
    shield: skreecustom_right nice_view_adapter nice_view
  - board: xiao_ble//zmk
    shield: settings_reset
